### ISSUE TITLE
unmarshal errors?

### ISSUE THREAD

**Issue by theganyo** [apid/apidVerifyApiKey#28]
Seeing "unmarshal errors" in the log during normal operation. It doesn't appear to cause improper behavior, but it is a bit concerning as it declares that it's an "error" - but is logged at debug level.

Log:
```
time="Nov 15 17:35:01.439" level=debug msg="{verify 4XlHFNPEhEhiXI305iayNfNdxPmGJ /get edgex01 test helloworld true}"
time="Nov 15 17:35:01.440" level=debug msg="unmarshall error for string, performing custom unmarshal {helloworld} and result is : [helloworld]"
time="Nov 15 17:35:01.441" level=debug msg="unmarshall error for string, performing custom unmarshal {test} and result is : [test]"
time="Nov 15 17:35:01.441" level=debug msg="unmarshall error for string, performing custom unmarshal {/**} and result is : [/**]"
time="Nov 15 17:35:01.441" level=debug msg="Api products retrieved for key : [%s] , tenantId : [%s] is 4XlHFNPEhEhiXI305iayNfNdxPmGJ[{d1fcf825-1f3a-4578-922b-08a12xb5aba6 helloworld helloworld  0   2017-10-23 22:38:54.287+00:00 theganyo@google.com 2017-10-23 22:38:54.287+00:00 theganyo@google.com  [test] [helloworld] [] [/**]}]"
```

**Comment by haomingzhang** [comment]
This is not an error. The debug message is somewhat misleading.
The context is: a column whose type is array is assumed to store a JSON in sqlite. However this is not true for many data we got from mgmt server. The field may be invalid json like `{a,b}`, so we're performing custom unmarshal. That's by design.

**Comment by theganyo** [comment]
In that case, the log message should be improved.

**Comment by rajanishgj** [comment]
Its indicating the unmarshal failed and hence performing customer unmarshal. 
The custom unmarshal is performed to handle incorrect legacy system. Its logged at debug level and not error, If it helps message can be improved but would leave the debug log. BTW the custom unmarshal also assumes specific format.

**Comment by theganyo** [comment]
I think we should strive for clarity in logging as logs will be read by people that won't know the background. But it sounds like you're saying that I shouldn't get this if I don't have an "incorrect legacy system". What does that mean? Why/how does this have an incorrect legacy system?

**Comment by rajanishgj** [comment]
Agree to clarity in logging. Please suggest.

Regarding the backend, system stores the value `{helloworld}` and this is expected to be json array, which is not correct. The correct value would be `["helloworld"]` and verify api key plugin is trying to parse the change as json, fails and falls back to custom parse.

**Comment by theganyo** [comment]
Right, I understand what it's expecting. I'm just wondering: Why are we storing the wrong thing? Is there a bug? Are we in transition?
